/**
 * Created by Chris Ho on 7/26/2016.
 */

import batTrangImg from './images/bat-trang-village.jpg';

export const COUNTRY_DATA = [
  'Afghanistan',
  'Aland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bonaire, Saint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, The Democratic Republic of the',
  'Cook Islands',
  'Costa Rica',
  'Cote d’Ivoire',
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic of',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, Democratic People’s Republic of',
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People’s Democratic Republic',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Barthelemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Other',
];
export const DATA_TOUR = [
  {
    id: 'tour01',
    url: require('./images/oldquater.jpg'),
    name: 'Old Quarter walking Tour',
    time: [
      '6:00-9:00',
      '9:00-12:00',
      '14:00-17:00',
      '18:00-21:00',
      '9:00-17:00',
    ],
    description: [
      'Sword Lake',
      'Old quarter introduction',
      'Ancient  House,  No.87  Ma  May  Str',
      'Egg Coffee - Giảng/Đinh Coffee',
      'Quan Đế Temple - No.28 Hang Buom Str',
      'Bạch Mã (White Horse) Temple - No.76 Hang Buom Str',
      'Đồng Xuân Market',
      'No.48 Hang Ngang Str (where Ho Chi Minh stayed and wrote Declaration of Indepenece)',
      'Ca Tru Singing (optional)',
      'Water Puppetry (optional)',
    ],
  },
  {
    id: 'tour02',
    url: require('./images/war-site.jpg'),
    name: 'French Quarter walking Tour',
    time: [
      '6:00-9:00',
      '9:00-12:00',
      '14:00-17:00',
      '18:00-21:00',
      '9:00-17:00',
    ],
    description: [
      'Sword Lake',
      "St. Joseph's Cathedral, Cong Caphe",
      'Hoa lo Prison',
      'Trang Tien Ice Cream',
      'Opera House, and Hilton Opera',
      'National History Museum (optional)',
    ],
  },
  {
    id: 'tour03',
    url: require('./images/war-site.jpg'),
    name: 'War sites walking Tour',
    time: ['9:00-12:00', '14:00-17:00', '9:00-17:00'],
    description: [
      'Hoa lo Prison (highly recommended)',
      'Military History Museum (highly recommended)',
      'Ho Chi Minh Museum (recommended)',
      "Vietnam People's Air Force Museum (optional)",
      'Hanoi B52 Victory Museum (optional)',
      'B-52 Wreck in Huu Tiep Lake  (optional)',
    ],
  },
  {
    id: 'tour04',
    url: require('./images/city.jpg'),
    name: 'City Tour',
    time: [
      '6:00-9:00',
      '9:00-12:00',
      '14:00-17:00',
      '18:00-21:00',
      '9:00-17:00',
    ],
    description: [
      'Sword lake (recommended)',
      'Old quarter (recommended)',
      'Ho Chi Minh Complex (recommended): Mausoleum, Museum, Presidential palace',
      'Temple of Literature (recommended)',
      'Hoa Lo Prison (recommended)',
      'Hoa Lo prison',
      'National History Museum (recommended)',
    ],
  },
  {
    id: 'tour05',
    url: require('./images/tg5.jpg'),
    name: 'Street food Tour',
    time: ['18:00-21:00'],
    description: [
      'Phở (noodle) Lý Quốc Sư',
      'Phở 49 Bát Đàn',
      'Phở Sướng số 14 Ngõ Trung Yên, Đinh Liệt',
      'Phở Thìn 13 Lò Đúc',
      'Phở Thìn Bờ Hồ (61 Đinh Tiên Hoàng)',
      'Bún chả Hàng Mành (No.1 Hàng Mành)',
      'Bún chả Hàng Than (34 Hàng Than)',
      'Bún chả Obama (24 Lê Văn Hưu)',
      'Bánh Mì 25 Hàng Cá',
      'Others (optional)',
    ],
  },
  {
    id: 'tour06',
    url: require('./images/tg4.jpg'),
    name: 'Early Morning Tour',
    time: ['6:00-9:00'],
    description: [
      'Flag salute ceremony',
      'Quảng Bá Flower Market',
      "Old Quarter Locals' morning routine",
      'Breakfast',
      'Hồ Tây (West Lake) early market (optional)',
    ],
  },
  {
    id: 'tour07',
    url: require('./images/museum.jpg'),
    name: 'Museum Tour',
    time: ['9:00-12:00', '14:00-17:00', '9:00-17:00'],
    description: [
      'Hoa Lo Prision',
      'Vietnam Women Museum',
      'History Museum',
      'Military History Museum',
      'Ho Chi Minh Museum',
    ],
  },
  {
    id: 'tour08',
    url: batTrangImg,
    name: 'Craft Village - Half or Full day',
    time: ['9am-12am', '2pm-5pm', '9am-5pm'],
    description: [
      'Bat Trang Ceramic Village',
      'Van Phuc Silk Village',
      'Chuong Conical Hat Village',
      'Đông Hồ folk woodcut painting',
    ],
  },
  {
    id: 'tour09',
    url: require('./images/duong_lam.jpg'),
    name: 'Ancient Village - Half or Full day',
    time: ['9:00-12:00', '14:00-17:00', '9:00-17:00'],
    description: ['Đường Lâm Ancient Village', 'Bat Trang Ceramic Village'],
  },
  {
    id: 'tour10',
    url: require('./images/efis-tour.jpg'),
    name: 'Culture Exchange – Half or full day ',
    time: ['9:00-12:00', '14:00-17:00', '9:00-17:00'],
    description: [
      'Join club with local students (club’s members) – Hanoi Free Private Tour Guide’s office',
      'Cooking club - Hanoi Free Private Tour Guide’s office',
    ],
  },
];

export const DATA_PRICING = [
  {
    header: 'SCREEN',
    description: 'Screen for culture fit',
    modules: [
      { type: 'FLOW Motivator Report' },
      { type: '' },
      { type: '' },
      { type: '' },
      { type: 'Support & training', content: ['Support pack for HR'] },
    ],
    price: 99,
  },
  {
    header: 'ENGAGE',
    description: 'Boost employee engagement',
    modules: [
      { type: 'FLOW Motivator Report' },
      { type: 'FLOW Engagement Report' },
      { type: '' },
      { type: '' },
      {
        type: 'Support & training',
        content: [
          'Support pack for HR/line managers',
          '10 hours of implementation support',
        ],
      },
    ],
    price: 199,
  },
  {
    header: 'TEAM',
    description: 'Boost, benchmark and predict employee engagement',
    modules: [
      { type: 'FLOW Motivator Report' },
      { type: 'FLOW Engagement Report' },
      { type: 'FLOW Culture Report' },
      { type: '' },
      {
        type: 'Support & training',
        content: [
          'Support pack for HR/line managers',
          '20 hours of implementation support',
          'Superuser training for HR',
        ],
      },
    ],
    price: 299,
  },
  {
    header: 'ENTERPRISE',
    description:
      'Boost, benchmark and predict employee engagement and assess culture fit with custom algorithms',
    modules: [
      { type: 'FLOW Motivator Report' },
      { type: 'FLOW Engagement Report' },
      { type: 'FLOW Culture Report' },
      { type: 'FLOW Custom Reports' },
      {
        type: 'Support & training',
        content: [
          'Support pack for HR/line managers',
          'Continuous support in business hours',
          'Superuser training for HR/managers',
        ],
      },
    ],
    price: 399,
  },
];

export const DATE_FEATURES = [
  {
    urlImg: require('./images/tourguide-intro1.jpg'),
    headline: 'Supplying free services for foreign visitors',
    content:
      'Hanoi free private tour guide does free guiding with the aims of' +
      ' supplying free services for foreign visitors.',
  },
  {
    urlImg: require('./images/tg4.jpg'),
    headline:
      'Advertising Vietnam’s beauty: humans, sceneries, customs, cultures, cuisine.',
    content:
      '200 members are always ready to pick up guests. ' +
      '300+ tours have been taken, and we are heading to 1000 tours within 2016. ' +
      '40+ nations are where our guests come from.',
  },
  {
    urlImg: require('./images/tg6.jpg'),
    headline:
      'Chances for Vietnamese young generation to meet and learn from global citizens',
    content:
      'Advertising Vietnam’s beauty: humans, sceneries, customs, cultures, cuisine.' +
      ' chances for Vietnamese young generation to meet and learn from global citizens.' +
      ' We not only show you my country but also learn more from you.',
  },
];

export const DATA_ADDRESS = [
  {
    place: 'Hanoi',
    national: 'Hanoi',
    address: ['206A TTQKTD', '241 Mai Dich, Cau Giay, Hanoi'],
    urlMap:
      'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1565.6336899016342!2d105.77395279484446!3d21.043668809821426!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454ceb5427fff%3A0xacb7494300b4bded!2zTmfDtSAyNDEgTWFpIEThu4tjaCwgTWFpIEThu4tjaCwgQ-G6p3UgR2nhuqV5LCBIw6AgTuG7mWksIFZpZXRuYW0!5e0!3m2!1sen!2s!4v1473417939429',
  },
];

export const DATA_COMMENTS = [
  {
    quotation:
      'Free tours of Hanoi - because students want to gain an insight into your culture, ' +
      'share their culture and practise their english ... fantastic. ' +
      'Three of us, including our 13 y old were met at our hotel by Huong and her young assistant ' +
      '(who was in-training) .. Smiles and greetings all round - I immediately knew we were in for...',
    urlAvatar: require('./images/tour_comment6.jpg'),
    name: 'Anne Bertucio',
    country: 'USA',
    date: '22/06/2016',
    tour: 'Old Quarter walking Tour',
  },
  {
    quotation:
      'Hey Jenny, we really love your country allready. ' +
      'It was such a nice day walking with you two! Thank you so much. ' +
      "We just arrived in our Hotel in Danang. I'm pretty sure that we will have a great time here also. " +
      'Hope we can see wach other one day in Germany! You are allways welcome to stay at ms house. ' +
      'Just write me or with you have a question finding a scholarship I will try to hell you. ' +
      'Good night. Madlen',
    urlAvatar: require('./images/tour_comment5.jpg'),
    name: 'Madlen Maier',
    country: 'Canada',
    date: '18/08/2016',
    tour: 'Museum Tour',
  },
  {
    quotation:
      'Hi guys thank you so much for showing us around your wonderful city. ' +
      'you were great guides and really nice people. We are going to the markets ' +
      'tonight and then we are off to Hoi an. hopefully next time we meet our Vietnamese ' +
      "will be better and you'll be speaking better English than us. we wish you all the " +
      'best for you and your families and hopefully we will see you again, maybe even in Tasmania? ' +
      'lots of love, hugs and kisses - Ben and Kim. tam biet',
    urlAvatar: require('./images/tour_comment4.jpg'),
    name: 'Ben Bridgman',
    country: 'US',
    date: '28/05/2016',
    tour: 'Street food Tour',
  },
  {
    quotation:
      'Hello Jenny, how are you?? Our friends Lucia and Maia told us to contact you for the walking tour through Hanoi ' +
      'We arrived from sapa yesteday very late at night, it was such a wonderful experince ' +
      'We have two days in the city and wanted to know if today tou are available at any time to organize a tour guide with you',
    urlAvatar: require('./images/tour_comment3.jpg'),
    name: 'Clara Mallea Gil',
    country: 'Australia',
    date: '18/03/2016',
    tour: 'War sites walking Tour',
  },
  {
    quotation:
      'Thanks so much, Quy! It was a wonderful tour and Vietnam has so many kinds of food ' +
      "and they are all the best. Haven't had anything I didn't like. " +
      'Take are and I know you will go to New York and love it ',
    urlAvatar: require('./images/tour_comment2.jpg'),
    name: 'Irina Sjursen',
    country: 'Germany',
    date: '13/11/2015',
    tour: 'French Quarter walking Tour',
  },
  {
    quotation:
      'Haha definitely 🙂 ' +
      "I just met a friend's friend last night. She is going to study marketing overseas. " +
      'If you want, I might be able to send her note, and link the two of you together.',
    urlAvatar: require('./images/tour_comment1.jpg'),
    name: 'Yee Qing Xiang',
    country: 'Taiwan',
    date: '25/06/2016',
    tour: 'Old Quarter walking Tour',
  },
];
